version: '3'
services:
  billpayment-mysql:
    image: mysql:8.0.18
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - c:/billpaymentdb:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
